# Fabric notebook source

# METADATA ********************

# META {
# META   "kernel_info": {
# META     "name": "synapse_pyspark"
# META   },
# META   "dependencies": {
# META     "lakehouse": {
# META       "default_lakehouse": "9ef2f10f-d9a6-45da-90f6-0e17841b6d90",
# META       "default_lakehouse_name": "Zava_Lakehouse",
# META       "default_lakehouse_workspace_id": "524dfea1-0c59-477f-81bd-f4ad4461d8b9",
# META       "known_lakehouses": [
# META         {
# META           "id": "9ef2f10f-d9a6-45da-90f6-0e17841b6d90"
# META         }
# META       ]
# META     }
# META   }
# META }

# CELL ********************

# Import necessary libraries
import pandas as pd
from pyspark.sql import SparkSession
from pyspark.sql.functions import *
from pyspark.sql.types import *
import os

# Display Spark configuration
print(f"Spark Version: {spark.version}")
print(f"Application Name: {spark.sparkContext.appName}")
print("\nEnvironment ready for data upload!")

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Perform data exploration for data science

# Use the code in this notebook to perform data exploration for data science.

# Azure storage access info for open dataset diabetes
blob_account_name = "azureopendatastorage"
blob_container_name = "ojsales-simulatedcontainer"
blob_relative_path = "oj_sales_data"
blob_sas_token = r"" # Blank since container is Anonymous access

# Set Spark config to access  blob storage
wasbs_path = f"wasbs://%s@%s.blob.core.windows.net/%s" % (blob_container_name, blob_account_name, blob_relative_path)
spark.conf.set("fs.azure.sas.%s.%s.blob.core.windows.net" % (blob_container_name, blob_account_name), blob_sas_token)
print("Remote blob path: " + wasbs_path)

# Spark reads csv
df = spark.read.csv(wasbs_path, header=True)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.show()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.write.format('delta') \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .option('path', 'Tables/oj_sales_data') \
    .saveAsTable('oj_sales_data')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC select * FROM oj_sales_data LIMIT 10

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df = spark.read.format("delta").load(path="Tables/oj_sales_data")
display(df)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.sql import functions as F
from pyspark.sql import types as T

def clean_data(df):
    # Change column type to datetime64[ns] for column: 'WeekStarting'
    # ⚠️ Timestamp format may not be supported. Please check the results and modify if needed.
    df = df.withColumn('WeekStarting', df['WeekStarting'].cast(T.TimestampType()))
    # Change column type to float64 for columns: 'Price', 'Revenue', 'Quantity'
    df = df.withColumn('Price', df['Price'].cast(T.DoubleType()))
    df = df.withColumn('Revenue', df['Revenue'].cast(T.DoubleType()))
    df = df.withColumn('Quantity', df['Quantity'].cast(T.DoubleType()))
    # Change column type to int32 for column: 'Store'
    df = df.withColumn('Store', df['Store'].cast(T.IntegerType()))
    # Change column type to bool for column: 'Advert'
    df = df.withColumn('Advert', df['Advert'].cast(T.BooleanType()))
    # Replace all instances of "." with " " in column: 'Brand'
    df = df.withColumn('Brand', F.regexp_replace('Brand', "(?i)\\.", " "))
    # Capitalize the first character in column: 'Brand'
    df = df.withColumn('Brand', F.initcap(F.col('Brand')))
    return df

df_clean = clean_data(df)
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df.write.format('parquet') \
    .mode("overwrite") \
    .option("overwriteSchema", "true") \
    .option('path', 'Files/oj_sales_data') \
    .save()

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.sql import functions as F
from pyspark.sql import types as T

def clean_data(df):
    # Change column type to int32 for column: 'Quantity'
    df = df.withColumn('Quantity', df['Quantity'].cast(T.IntegerType()))
    # Change column type to int8 for column: 'Advert'
    df = df.withColumn('Advert', df['Advert'].cast(T.ByteType()))
    # Change column type to float32 for column: 'Price'
    df = df.withColumn('Price', df['Price'].cast(T.FloatType()))
    # Change column type to float64 for column: 'Revenue'
    df = df.withColumn('Revenue', df['Revenue'].cast(T.DoubleType()))
    # Change column type to int32 for column: 'Store'
    df = df.withColumn('Store', df['Store'].cast(T.IntegerType()))
    # Change column type to datetime64[ns] for column: 'WeekStarting'
    # ⚠️ Timestamp format may not be supported. Please check the results and modify if needed.
    df = df.withColumn('WeekStarting', df['WeekStarting'].cast(T.TimestampType()))
    # Replace all instances of "." with " " in column: 'Brand'
    df = df.withColumn('Brand', F.regexp_replace('Brand', "(?i)\\.", " "))
    # Capitalize the first character in column: 'Brand'
    df = df.withColumn('Brand', F.initcap(F.col('Brand')))
    return df

df_clean = clean_data(df)
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean.write.format('delta') \
    .option('path', 'Tables/oj_sales_clean') \
    .saveAsTable('oj_sales_clean')

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# MAGIC %%sql
# MAGIC Select * FROM oj_sales_clean LIMIT 100

# METADATA ********************

# META {
# META   "language": "sparksql",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

df_clean = spark.read.format("delta").load(path="Tables/oj_sales_clean")
display(df_clean)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.sql import functions as F

def clean_data(df_clean):
    # Replace all instances of "." with " " in column: 'Brand'
    df_clean = df_clean.withColumn('Brand', F.regexp_replace('Brand', "(?i)\\.", " "))
    return df_clean

df_clean_1 = clean_data(df_clean)
display(df_clean_1)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }

# CELL ********************

# Code generated by Data Wrangler for PySpark DataFrame

from pyspark.ml.feature import StringIndexer, OneHotEncoder
from pyspark.ml.functions import vector_to_array
from pyspark.sql import functions as F

def clean_data(df_clean_1):
    # One-hot encode column: 'Brand'
    # ⚠️ This was generated to match the original pandas logic but may have performance issues.
    def one_hot_encode_col(df, key):
        insert_idx = df.columns.index(key)
        indexer = StringIndexer(inputCol=key, outputCol='%s_numeric' % str(key), handleInvalid='keep')
        indexer_fitted = indexer.fit(df)
        df_indexed = indexer_fitted.transform(df)
        encoder = OneHotEncoder(inputCols=['%s_numeric' % str(key)], outputCols=['%s_onehot' % str(key)], dropLast=False)
        df_onehot = encoder.fit(df_indexed).transform(df_indexed)
        df_col_onehot = df_onehot.select('*', vector_to_array('%s_onehot' % str(key)).alias('%s_col_onehot' % str(key)))
        labels = sorted(indexer_fitted.labels)
        cols_expanded = [(F.col('%s_col_onehot' % str(key))[i].alias('%s_%s' % (str(key), labels[i]))) for i in range(len(labels))]
        df = df_col_onehot.select(*df.columns[:insert_idx], *cols_expanded, *df.columns[insert_idx+1:])
        return df
    df_clean_1 = one_hot_encode_col(df_clean_1, 'Brand')
    return df_clean_1

df_clean_2 = clean_data(df_clean_1)
display(df_clean_2)

# METADATA ********************

# META {
# META   "language": "python",
# META   "language_group": "synapse_pyspark"
# META }
