CREATE VIEW [dbo].[vFactSales]
AS
	SELECT
		CAST(N'Reseller' AS NVARCHAR(10)) AS [Channel]
		,CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) AS [SalesOrderKey]
		,((CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) * 1000) + [SalesOrderLineNumber]) AS [SalesOrderLineKey]
		,[SalesOrderNumber]
		,[SalesOrderLineNumber]
		,[ResellerKey]
		,CAST(-1 AS INT) AS [CustomerKey]
		,[ProductKey]
		,[OrderDateKey]
		,[DueDateKey]
		,[ShipDateKey]
		,[PromotionKey]
		,[CurrencyKey]
		,[SalesTerritoryKey]
		,[EmployeeKey]
		,[OrderQuantity]
		,[UnitPrice]
		,[ExtendedAmount]
		,[UnitPriceDiscountPct]
		,[DiscountAmount]
		,[ProductStandardCost]
		,[TotalProductCost]
		,[SalesAmount]
		,[TaxAmount]
		,[FreightAmount]
		,[CarrierTrackingNumber]
		,[CustomerPONumber]
		,[RevisionNumber]
	FROM
		[dbo].[FactResellerSales]
	UNION ALL
	SELECT
		CAST(N'Internet' AS NVARCHAR(10)) AS [Channel]
		,CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) AS [SalesOrderKey]
		,((CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) * 1000) + [SalesOrderLineNumber]) AS [SalesOrderLineKey]
		,[SalesOrderNumber]
		,[SalesOrderLineNumber]
		,CAST(-1 AS INT) AS [ResellerKey]
		,[CustomerKey]
		,[ProductKey]
		,[OrderDateKey]
		,[DueDateKey]
		,[ShipDateKey]
		,[PromotionKey]
		,[CurrencyKey]
		,[SalesTerritoryKey]
		,CAST(-1 AS INT) AS [EmployeeKey]
		,[OrderQuantity]
		,[UnitPrice]
		,[ExtendedAmount]
		,[UnitPriceDiscountPct]
		,[DiscountAmount]
		,[ProductStandardCost]
		,[TotalProductCost]
		,[SalesAmount]
		,[TaxAmount]
		,[FreightAmount]
		,[CarrierTrackingNumber]
		,[CustomerPONumber]
		,[RevisionNumber]
	FROM
		[dbo].[FactInternetSales];

GO

