CREATE VIEW [dbo].[vFactSales2]
WITH SCHEMABINDING
AS
	SELECT
		CAST(N'Reseller' AS NVARCHAR(10)) AS [Channel]
		,CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) AS [SalesOrderKey]
		,((CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) * 1000) + [SalesOrderLineNumber]) AS [SalesOrderLineKey]
		,[SalesOrderNumber]
		,[SalesOrderLineNumber]
		,CAST([dod].[FullDateAlternateKey] AS DATETIME) AS [OrderDate] --Date/time columns required for incremental refresh
		,CAST([ddd].[FullDateAlternateKey] AS DATETIME) AS [DueDate]
		,CAST([dsd].[FullDateAlternateKey] AS DATETIME) AS [ShipDate]
		,[ResellerKey]
		,CAST(-1 AS INT) AS [CustomerKey]
		,[ProductKey]
		,[PromotionKey]
		,[CurrencyKey]
		,[SalesTerritoryKey]
		,[EmployeeKey]
		,[OrderQuantity]
		,[UnitPrice]
		,[ExtendedAmount]
		,[UnitPriceDiscountPct]
		,[DiscountAmount]
		,[ProductStandardCost]
		,[TotalProductCost]
		,[SalesAmount]
		,[TaxAmount]
		,[FreightAmount]
		,[CarrierTrackingNumber]
		,[CustomerPONumber]
		,[RevisionNumber]
	FROM
		[dbo].[FactResellerSales] AS [rs]
		LEFT JOIN [dbo].[DimDate] AS [dod]
			ON [dod].[DateKey] = [rs].[OrderDateKey]
		LEFT JOIN [dbo].[DimDate] AS [ddd]
			ON [ddd].[DateKey] = [rs].[DueDateKey]
		LEFT JOIN [dbo].[DimDate] AS [dsd]
			ON [dsd].[DateKey] = [rs].[ShipDateKey]
	UNION ALL
	SELECT
		CAST(N'Internet' AS NVARCHAR(10)) AS [Channel]
		,CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) AS [SalesOrderKey]
		,((CAST(RIGHT([SalesOrderNumber], (LEN([SalesOrderNumber]) - 2)) AS INT) * 1000) + [SalesOrderLineNumber]) AS [SalesOrderLineKey]
		,[SalesOrderNumber]
		,[SalesOrderLineNumber]
		,CAST([dod].[FullDateAlternateKey] AS DATETIME) AS [OrderDate] --Date/time columns required for incremental refresh
		,CAST([ddd].[FullDateAlternateKey] AS DATETIME) AS [DueDate]
		,CAST([dsd].[FullDateAlternateKey] AS DATETIME) AS [ShipDate]
		,CAST(-1 AS INT) AS [ResellerKey]
		,[CustomerKey]
		,[ProductKey]
		,[PromotionKey]
		,[CurrencyKey]
		,[SalesTerritoryKey]
		,CAST(-1 AS INT) AS [EmployeeKey]
		,[OrderQuantity]
		,[UnitPrice]
		,[ExtendedAmount]
		,[UnitPriceDiscountPct]
		,[DiscountAmount]
		,[ProductStandardCost]
		,[TotalProductCost]
		,[SalesAmount]
		,[TaxAmount]
		,[FreightAmount]
		,[CarrierTrackingNumber]
		,[CustomerPONumber]
		,[RevisionNumber]
	FROM
		[dbo].[FactInternetSales] AS [is]
		LEFT JOIN [dbo].[DimDate] AS [dod]
			ON [dod].[DateKey] = [is].[OrderDateKey]
		LEFT JOIN [dbo].[DimDate] AS [ddd]
			ON [ddd].[DateKey] = [is].[DueDateKey]
		LEFT JOIN [dbo].[DimDate] AS [dsd]
			ON [dsd].[DateKey] = [is].[ShipDateKey];

GO

